### ISSUE TITLE
AnimationManager

### ISSUE THREAD

**Issue by theligero** [ivo-hr/super-proj-melee#34]
- [x] Capacidad de procesar spritesheets.
- [x] Contador de frames por sprite.
- [x] Comunicación con clase Entity.
- [x] Averiguar como invertir sprites y hacerlo

**Comment by Yavi123** [comment]
- [ ] Capacidad de procesar spritesheets.
- [ ] Contador de frames por sprite.
- [ ] Comunicación con clase Entity.
