### ISSUE TITLE
Inicio del arte de escenario

### ISSUE THREAD

**Issue by Edu-git1** [ivo-hr/super-proj-melee#6]
Tener un fondo de escenario y un diseño básico de plataforma y/o base del escenario.

**Comment by Edu-git1** [comment]
- [ ] dfugyoaisdyfoaisdufoaisudf

- [ ] asdfiouasyhdpoifhpaosdif

- [ ] asdifuypasiudpfi

**Comment by theligero** [comment]
- [ ] Hola

**Comment by Edu-git1** [comment]
- [ ] Tener un fondo base del escenario
- [ ] Tener un diseño base de plataforma acorde al diseño del escenario
- [ ] Tener el mismo escenario y plataformas con un par de cambios de gama de colores.
